#define TOK_START 1
#define TOK_STOP 2
#define TOK_ADD 3
#define TOK_VAR 4
#define TOK_SUB 5
#define TOK_MULT 6
#define TOK_LOAD 7
#define TOK_STORE 8
#define TOK_TRANS 9
#define TOK_TRIM 10
#define TOK_DIV 11
#define TOK_READ 12
#define TOK_PRINT 13
#define TOK_LIR 14
#define TOK_NUM 15
#define TOK_COMMA 16
#define TOK_IIR 17
#define TOK_LOOP 18
#define TOK_DS 19
#define TOK_DC 20
#define TOK_R4 21
#define TOK_R3 22
#define TOK_LTORG 23
#define TOK_END 24